### ISSUE TITLE
Add Description For C# Patterns

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#10]
If you notice through the readme of existing languages patterns, one column has been reserved for textual description of the corresponding pattern. 
To Do: Add description for each pattern present in the C# Patterns Section of the Repository in the future.

**Comment by trial1user** [comment]
Hey buddy I would like to take up this section of contributing Patterns in C#. Could you create a section like you did for the current three languages and I could start adding programs once I see the patterns and create programs?

**Comment by aryashah2k** [comment]
Would you like to add patterns and also add description or only one of those? Anyways thanks for reaching out, you can start working on C# Section and once you are ready, make your first pull request. I shall review it we can move along from there!

**Comment by aryashah2k** [comment]
Closing Issues Related To Writing Descriptions For Patterns Since The Pattern Images Might Be Self Explanatory For The User To Figure Out The Description O f The Pattern.
