### ISSUE TITLE
Add Java Pattern Programs

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#2]
The repository currently plans creating pattern programs in 3 languages -C,C++ and Python. I wished to see programs in Java Language as well. Reply to this section if you wish to have Java Pattern Programs Section assigned to you.

**Comment by khushali6** [comment]
I want to work on this issue. But What kind of pattern to create?

**Comment by aryashah2k** [comment]
Hi @khushali6 , thanks for showing interest in this repository and the willingness to contribute to the same. The patterns can be found in the Java Pattern folder assets. For eg, if you want to work on symbol patterns in Java, then this is the folder containing the patterns you can work on- https://github.com/aryashah2k/Printing-Pattern-Programs/tree/main/Java%20Pattern%20Programs/Symbol%20Patterns. 
Have a look at all the patterns in any of the folder and code for the patterns you are comfortable to write program on.
I am not well versed with Java but since it is an important language, I have recently added the section for Java and if you can show quality work with proper patterns. You can get access to this repo by becoming a contributor along with other folks like you who are currently working on the same repo but different languages.

Fir a complete readme of how the sections will look under each language, Check this out. https://github.com/aryashah2k/Printing-Pattern-Programs/blob/main/C%2B%2B%20Pattern%20Programs/README.md
Here I have wriiten pattern programs for certain patterns and the final readme layout is complete.

All the best and let me know if you are comfortable in working for this repo. I will thereafter assign the relevant issue to you!
Good Luck!

**Comment by khushali6** [comment]
Thank You So much for guiding me. I would like to work on Even Number Series on https://github.com/khushali6/Printing-Pattern-Programs/blob/main/Java%20Pattern%20Programs/Series%20Patterns/Even%20Number%20Series.jpg

**Comment by khushali6** [comment]
public class Even{

     public static void main(String []args){
       int n=100;
       for(int i=1;i<n;i++){
           if(i%2==0)
           System.out.print(i+" ");
           
       }
       
     }
}

**Comment by aryashah2k** [comment]
Hello again😃, Great to see you've identified the patterns and started to write programs for the same. I see you mentioned your program here directly. There's a better way to contribute your code on not only this repo but any repo you wish to contribute on Github in the future and I feel you should start contributing like a pro on my repo and learn along the way!
So the very first thing you need to do is create a new issue and mention the pattern you are solving.
Secondly fork this repo(star if you want 😃) and then push the code locally and then create a pull request. I will then be able to review your code, test it and merge it.
If there is any doubt feel free to reach out.

**Comment by aryashah2k** [comment]
Individual Issues To Be Opened For Each Type Of Pattern Section Moving Forward From Here.
