### ISSUE TITLE
Add Java Wave Patterns

### ISSUE THREAD

**Issue by trial1user** [aryashah2k/Printing-Pattern-Programs#21]
Hi, I could work on completing the wave patterns under the java section

**Comment by aryashah2k** [comment]
Hello, thanks for showing interest in contributing to this repository, I am assigning this issue to you and once completed, you can create your pull request and I'll review it.

**Comment by aryashah2k** [comment]
Hi there, the PR has been successfully merged for patterns 1 - 17. Looking forward to have you complete the whole section and will close this issue thereon.
Thanks a lot for the contributions!

**Comment by aryashah2k** [comment]
The Java Wave Patterns Section has been completed . Thanks @trial1user for your efforts towards this contributions. Feel free to work on other issues or open new ones that can help complete this repository!
