### ISSUE TITLE
Add Java Series Patterns

### ISSUE THREAD

**Issue by neelima-girlcoder** [aryashah2k/Printing-Pattern-Programs#24]
@aryashah2k  ,I would like to start contributing patterns code for series pattern in Java

**Comment by aryashah2k** [comment]
Sure Please go ahead with the creation of series patterns for Java . I have assigned this issue to you. Thanks for the contributions on spiral patterns too!

**Comment by aryashah2k** [comment]
Issue Successfully Addressed and PR Merged! Credits to : @neelima-girlcoder
