### ISSUE TITLE
Add Pyramid Patterns | Java

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#27]
Add Code files for various pyramid patterns under the Java Folder Section

**Comment by aryashah2k** [comment]
Hey @aryashah2k , I can work on pyramid patterns for java. I have previously worked on Java Wave patterns. you can assign this issue to me.

**Comment by trial1user** [comment]
Hey @aryashah2k , I can work on pyramid patterns for java. I have previously worked on Java Wave patterns. you can assign this issue to me.

**Comment by aryashah2k** [comment]
Hey there @trial1user , that's some really amazing work. Thanks a lot for working on this. I have successfully merged the PR. Grateful to have your contributions towards this repository!
