### ISSUE TITLE
Add Symbol Patterns | Java

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#29]
Add Code files for various symbol patterns under the Java Folder Section

**Comment by neelima-girlcoder** [comment]
Hey @aryashah2k , I can work on the symbol patterns for java. If you found my previous work useful, please consider assigning me this issue!

**Comment by aryashah2k** [comment]
Hi @neelima-girlcoder , Your previous work was amazing and has tremendously benefitted this repository. You can surely work on the symbol patterns. Since this is a long one - around 79 patterns, I request you to take your time and you can submit code files in blocks of 10 or whatever number suits you. I dont expect to get all codes in one shot. All the best and keep me updated with your progress!

**Comment by aryashah2k** [comment]
Hey @neelima-girlcoder , I've reviewed all your PRs and Thanks to you, the symbol patterns section for Java is complete. You've done a great job, thanks for your contributions, feel free to take up any other issue or create one. All the best
Regards, Arya.
