### ISSUE TITLE
Add Description For Python Patterns

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#7]
If you notice through the readme, one column is reserved for textual description of the corresponding pattern. 
To Do: Add description for each pattern present in the Python Patterns Section of the Repository.

**Comment by ajaygtm71** [comment]
can you give a sample of the description to be added.  Do you mean explanation of the code?

**Comment by aryashah2k** [comment]
Hi Ajay, thanks for reaching out,
Sure , this is what I am trying to convey:
![image](https://user-images.githubusercontent.com/73865728/103154684-04377100-47bf-11eb-8f40-48d20c868dce.png)

**Comment by aryashah2k** [comment]
> Hi Ajay, thanks for reaching out,
> Sure , this is what I am trying to convey:
> ![image](https://user-images.githubusercontent.com/73865728/103154684-04377100-47bf-11eb-8f40-48d20c868dce.png)

The reason behind this is that many patterns are such that require verbal explanation in order to understand what the pattern is about.(Spiral Patterns For Example) So, in order to maintain uniformity, it is better to add verbal description of all the programs since this repo is targeted towards beginner programmers and students who usually get such programs in their first year, for projects or might get asked in any contest or interview to check their knowledge of looping constructs

**Comment by aryashah2k** [comment]
Closing Issues Related To Writing Descriptions For Patterns Since The Pattern Images Might Be Self Explanatory For The User To Figure Out The Description O f The Pattern.
